# -*- coding: utf-8 -*-
"""FinVAR_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6r8i8FIA9U_zrwlKNBUi2JXSmd7Mcmn
"""

import streamlit as st
import yfinance as yf


st.title("📊 FinVAR – Your financial assistant referee")


user_input=st.text_input("Enter the ticker name:")

if user_input:
    ticker = yf.Ticker(user_input)
    st.subheader("Income Statement")
    st.dataframe(ticker.financials)

    st.subheader("Balance Sheet")
    st.dataframe(ticker.balance_sheet)

    st.subheader("Cash Flow")
    st.dataframe(ticker.cashflow)

