# -*- coding: utf-8 -*-
"""FinVAR_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6r8i8FIA9U_zrwlKNBUi2JXSmd7Mcmn
"""

import streamlit as st
import yfinance as yf

st.title("📊 FinVAR – Your Financial Assistant Referee")

user_input = st.text_input("Enter the ticker name:")

if user_input:
    ticker = yf.Ticker(user_input)
    info = ticker.info 
    st.header("🏢 Company Overview")
    company_name = info.get('longName', 'N/A')
    st.markdown(f"<h2 style='font-size:32px; color:#FFFFFF;'>🏢 Company Name: {company_name}</h2>", unsafe_allow_html=True)
    st.write(f"**Description:** {info.get('longBusinessSummary', 'N/A')}")

    price_data = ticker.history(period="1d")  # gets today’s data
    st.write("<h2 style='font-size:16px; color:#FFFFFF;'>Latest Close:", price_data['Close'].iloc[-1])
    
    st.subheader("Income Statement")
    st.dataframe(ticker.financials)

    st.subheader("Balance Sheet")
    st.dataframe(ticker.balance_sheet)

    st.subheader("Cash Flow")
    st.dataframe(ticker.cashflow)
