# -*- coding: utf-8 -*-
"""FinVAR_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6r8i8FIA9U_zrwlKNBUi2JXSmd7Mcmn
"""

import streamlit as st
import yfinance as yf

st.markdown(
    """
    <style>
    .stApp {
        background-color: #f0f2f6;
        color: #1a1a1a;
    }
    .big-title {
        font-size: 48px;
        font-weight: 800;
        color: #00C49A;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="big-title">FinVAR – Your financial assistant referee</div>', unsafe_allow_html=True)

st.title("📊 FinVAR – Your financial assistant referee")


user_input=st.text_input("Enter the ticker name:")

if user_input:
    ticker = yf.Ticker(user_input)
    st.subheader("Income Statement")
    st.dataframe(ticker.financials)

    st.subheader("Balance Sheet")
    st.dataframe(ticker.balance_sheet)

    st.subheader("Cash Flow")
    st.dataframe(ticker.cashflow)

