# -*- coding: utf-8 -*-
"""FinVAR_Button_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtQlY2vsf8O6B94jrhZy0CCbNxRJY1h2
"""

import yfinance as yf
import streamlit as st
st.set_page_config(page_title="FinVAR", layout="centered")
st.title("📊 FinVAR – Your Financial Assistant Referee")
user_input=input("Enter the ticker_name")

if user_input:
  ticker=yf.Ticker(user_input)
  info=ticker.info
  st.subheader("🏢 Company Name")
  st.write(info['longName'])
  if st.button("Display current price:"):
    st.subheader("💰 Current Price")
    st.write(info['currentPrice'])